apiVersion: v1
kind: Secret
metadata:
  name: php-monolith-secret
  namespace: knowledgecity
type: Opaque
stringData:
  CLICKHOUSE_USER: "default"
  CLICKHOUSE_PASSWORD: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-monolith-config
  namespace: knowledgecity
data:
  CLICKHOUSE_HOST: "clickhouse.knowledgecity.svc.cluster.local"
  CLICKHOUSE_PORT: "8123"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-monolith
  namespace: knowledgecity
  labels:
    app: php-monolith
spec:
  replicas: 2
  selector:
    matchLabels:
      app: php-monolith
  template:
    metadata:
      labels:
        app: php-monolith
    spec:
      containers:
      - name: php-monolith
        image: <AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/knowledgecity/php-monolith:latest
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: php-monolith-config
        - secretRef:
            name: php-monolith-secret
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: php-monolith
  namespace: knowledgecity
spec:
  selector:
    app: php-monolith
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: php-monolith-hpa
  namespace: knowledgecity
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: php-monolith
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: php-monolith-ingress
  namespace: knowledgecity
  annotations:
    kubernetes.io/ingress.class: alb # or nginx if using NGINX ingress controller
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
  - host: api.knowledgecity.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: php-monolith
            port:
              number: 80
