apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-monolith
  namespace: knowledgecity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-monolith
  template:
    metadata:
      labels:
        app: php-monolith
    spec:
      containers:
      - name: php-monolith
        image: php-monolith:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: php-monolith
  namespace: knowledgecity
spec:
  selector:
    app: php-monolith
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  type: NodePort
