loki:
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: gp2   # or your cloud storage class

promtail:
  enabled: true
  config:
    snippets:
      pipelineStages:
        - cri: {}
